name: LINE Notify Action
description: 利用LINE Notify進行CI結果通知

inputs:
  token:
    description: LINE Notify Token
    required: true
  job-status:
    required: true
runs:
  using: "composite"
  steps:
    - name: CI結果通知
      env:
        BUILD_LINK: ${{ gitea.server_url }}/${{ gitea.repository }}/actions/runs/${{ gitea.run_number }}
      run: |
        [[ ${{ inputs.job-status }} = "success" ]] && MSG="${{ vars.SUCCESS_MSG }}" || MSG="${{ vars.FAILURE_MSG }}"
        curl -d "message=%0A${{ gitea.repository }} ${{ gitea.ref_name }}版%0A${MSG}%0Alogs: ${BUILD_LINK}" -H "Authorization: Bearer ${{ inputs.token }}" -X POST https://notify-api.line.me/api/notify
